# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/spin/spin_plugin_common
      ref: v1.4.0
      file: ci/.gitlab-ci.yml

# ------------------------------------------------------------------------------
# FIXME: The following customizations must be removed as soon as spin_conpod
#        provides a valid documentation
.release_deps:
    needs:
        - wheel
        - job: test_linux
          artifacts: false
        - job: test_windows
          artifacts: false

documentation:
    rules:
        - when: never

pages:
    rules:
        - when: never
