# -*- mode: yaml; coding: utf-8 -*-

include:
    - project: qs/spin/spin_plugin_common
      ref: v2.0.1
      file: ci/.gitlab-ci.yml

.test_base:
    variables:
        COVERAGE_PATH: src/csspin_workflows
