# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
    os: ubuntu-24.04
    tools:
        python: '3.13'
    commands:
        # Upgrade needed due to dependency conflict with platformdirs (spin vs virtualenv)
        - python -m pip install --upgrade virtualenv
        - python -m pip install csspin
        - spin provision
        - spin docs html
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - mv doc/_build/html/* $READTHEDOCS_OUTPUT/html
